# Generated by Django 3.0.3 on 2020-06-26 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuestionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=200, null=True)),
                ('pregunta1', models.CharField(blank=True, max_length=200, null=True)),
                ('pregunta2', models.CharField(blank=True, max_length=200, null=True)),
                ('pregunta3', models.CharField(blank=True, max_length=200, null=True)),
                ('pregunta4', models.CharField(blank=True, max_length=200, null=True)),
                ('pregunta5', models.CharField(blank=True, max_length=200, null=True)),
                ('pregunta6', models.CharField(blank=True, max_length=200, null=True)),
                ('pregunta7', models.CharField(blank=True, max_length=200, null=True)),
                ('pregunta8', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
