# Generated by Django 3.0.3 on 2020-06-26 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppProyecto', '0002_cuestionario_pregunta9'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuestionario',
            name='pregunta9',
        ),
    ]
